# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2

updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    labels:
      - dependencies
    allow:
      - dependency-name: "org.apache.maven.plugins:*"
      - dependency-name: "org.codehaus.mojo:*"
      - dependency-name: "*jacoco*" # code coverae tool, both tool and plugin
      - dependency-name: "*plugin*"
    ignore:
      - dependency-name: "jaxb-xew-plugin" # updated with core
      - dependency-name: "*graalvm*" # do not touch graalvm related stuff
      - dependency-name: "org.openapitools:openapi*" # updated togeter with openapi genrator
      - dependency-name: "com.diffplug.spotless:spotless-maven-plugin" # updated together with SAT
