# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build knx addon with Maven

on:
  push:
    branches: [ pr-knx-data-secure, pr-knx-ip-secure]
  workflow_dispatch:



jobs:
  build340:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Build with Maven
      run: mvn -B package verify --file pom.xml -pl :org.openhab.binding.knx -Dohc.version=3.4.0
    - uses: actions/upload-artifact@v3
      with:
        name: org.openhab.binding.knx.340
        path: bundles/org.openhab.binding.knx/target/org.openhab.binding.knx-*.jar
    - name: Upload SAT Summary Report
      uses: actions/upload-artifact@v3
      with:
        name: sat-summary-report
        path: target/summary_report.html


  build34x:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Build with Maven
      run: mvn -B package verify --file pom.xml -pl :org.openhab.binding.knx
    - uses: actions/upload-artifact@v3
      with:
        name: org.openhab.binding.knx.400
        path: bundles/org.openhab.binding.knx/target/org.openhab.binding.knx-*.jar
    - name: Upload SAT Summary Report
      uses: actions/upload-artifact@v3
      with:
        name: sat-summary-report
        path: target/summary_report.html

