# This workflow triggers the ci_build workflow when a pull request
# is labeled with 'rebuild'.
name: Trigger ci_build on label
run-name: xx

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  trigger-build:
    if: ${{ github.event.label.name == 'rebuild' }}
    name: yy
    uses: ./.github/workflows/ci-build.yml
